# Generated by Django 3.2.13 on 2024-09-12 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.IntegerField()),
                ('auto', models.IntegerField()),
                ('two_wheeler', models.IntegerField()),
                ('heavy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=12)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('auto', 'Auto'), ('two_wheeler', 'Two Wheeler'), ('heavy', 'Heavy Vehicle')], max_length=12)),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.fair')),
            ],
        ),
    ]
