# Generated by Django 3.2.13 on 2024-09-12 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('fair', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='vehicleinfo',
            old_name='time',
            new_name='time_in',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='fair',
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='time_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='vehicle_out',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Fair',
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicletype'),
        ),
    ]
