# Generated by Django 3.2.13 on 2024-08-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#2E073F', max_length=7)),
                ('secondary_color', models.CharField(default='#AD49E1', max_length=7)),
                ('input_bg_color', models.CharField(default='#7A1CAC', max_length=7)),
                ('input_border_color', models.CharField(default='#2E073F', max_length=7)),
                ('input_border_focus_color', models.CharField(default='#2E073F', max_length=7)),
                ('input_text_color', models.CharField(default='#f1f1f1', max_length=7)),
                ('background_color', models.CharField(default='#EBD3F8', max_length=7)),
                ('cancel_color', models.CharField(default='#e74c3c', max_length=7)),
                ('save_color', models.CharField(default='#2E073F', max_length=7)),
                ('back_color', models.CharField(default='#f39c12', max_length=7)),
                ('reset_pass_color', models.CharField(default='#9b59b6', max_length=7)),
            ],
        ),
    ]
