# Generated by Django 3.2.13 on 2024-09-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorSettings',
        ),
    ]
